spring.application.name=creatorhub

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/creatorhub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

spring.web.resources.static-locations=classpath:/static/
server.port=8080

logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.web=INFO
youtube.api-key=${YOUTUBE_API_KEY}


